# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [3]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
print(np.version, np.show_config)

<module 'numpy.version' from '/Users/viktoriasazonova/opt/anaconda3/lib/python3.8/site-packages/numpy/version.py'> <function show at 0x7f9b743e19d0>


#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [20]:
def memory_size(arr):
    return arr.size * arr.itemsize
memory_size(np.zeros(10))

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [26]:
v = np.zeros(10)
v[4]=1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [30]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [38]:
np.arange(10,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [40]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [42]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [48]:
np.random.random(27).reshape(3, 3,  3)

array([[[0.80218597, 0.63442338, 0.14821296],
        [0.81834123, 0.93047632, 0.11218762],
        [0.16099971, 0.99560818, 0.88089129]],

       [[0.86476613, 0.30271858, 0.76596765],
        [0.00512733, 0.20853652, 0.73758074],
        [0.74407944, 0.12360808, 0.43975224]],

       [[0.11155202, 0.71576062, 0.28622628],
        [0.11242317, 0.45322407, 0.34535996],
        [0.41899685, 0.62321887, 0.06648069]]])

In [50]:
np.random.random((3,3,3))

array([[[0.33342156, 0.7969401 , 0.20374488],
        [0.95148301, 0.09448539, 0.36092744],
        [0.51378669, 0.77168031, 0.8863932 ]],

       [[0.7853445 , 0.93179753, 0.775335  ],
        [0.30615839, 0.62373568, 0.40624904],
        [0.39528325, 0.85239179, 0.88505669]],

       [[0.37231724, 0.98996264, 0.8860372 ],
        [0.66459926, 0.07924995, 0.03293986],
        [0.61662294, 0.75329243, 0.88460283]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [56]:
arr = np.random.random((10,10))
print(np.min(arr), np.max(arr))
print(arr.min(), arr.max())

0.01086707820570576 0.9958708745214809
0.01086707820570576 0.9958708745214809


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [57]:
np.random.random(30).mean()

0.4886818195591229

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [62]:
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [67]:
np.pad(arr, 1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [69]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [72]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [93]:
arr = np.zeros(64).reshape(8,8)
arr[::2, ::2]=1
arr[1::2, 1::2]=1
arr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [100]:
np.unravel_index(99, (6,7,8))


(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [103]:
np.tile( np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [106]:
arr=np.random.random((5,5))
(arr -arr.mean())/arr.std(0)

array([[-1.29118809,  1.4688028 , -1.8668688 ,  1.30617698, -0.9890294 ],
       [-1.28464069, -1.07085246, -2.28964391, -0.08895617,  1.19209168],
       [ 1.1717731 , -0.20527212, -0.80003115, -1.1586291 ,  1.15662891],
       [-0.12831782,  1.32060465,  0.2087052 ,  1.1166089 , -0.48362395],
       [-1.43193564,  1.15474387, -2.42400095, -0.8474852 ,  1.45439587]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [109]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [111]:
np.dot(np.random.random((5,3)), np.random.random((3,2)))

array([[1.11204324, 0.62141985],
       [0.65720992, 0.52315088],
       [1.25346955, 0.55392777],
       [1.3471868 , 0.67481861],
       [1.21017051, 0.79007111]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [117]:
arr = np.arange(11)
arr[(3 < arr) & (arr < 8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [120]:
sum(range(5),-1)
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [130]:
Z=np.arange(11)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z # no


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [131]:
np.array(0) / np.array(0)

<ipython-input-131-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [132]:
np.array(0) // np.array(0)

<ipython-input-132-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [133]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [142]:
Z = np.random.uniform(-10,+10,10)
print(np.where(Z<0, np.floor(Z), np.ceil(Z)))

[-10.   9.  -7.   9.  -5.   8.  10.  10.  -8.   3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [145]:
arr1 =  np.arange(11)
arr2 =  np.arange(2, 20)
print(np.intersect1d(arr1, arr2))

[ 2  3  4  5  6  7  8  9 10]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [154]:
defaults = np.seterr(all="ignore")
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [155]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [160]:
np.datetime64('today') - np.timedelta64(1)
np.datetime64('today')
np.datetime64('today') + np.timedelta64(1)

numpy.datetime64('2022-03-14')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [162]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [172]:
A = np.ones(1)
B = np.ones(1)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [183]:
arr = np.random.uniform(0,8,10)
arr
np.floor(arr)
arr//1
arr.astype(int)
np.trunc(arr)

array([0., 3., 6., 0., 0., 1., 3., 7., 3., 4.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [187]:
np.tile(np.arange(0, 5), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [194]:
def generate():
    for x in range(10):
        yield x
        
np.array(list(generate()))


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [196]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [201]:
arr = np.random.random(10)
arr.sort()
print(arr)

[0.06678201 0.07835493 0.07923547 0.08498629 0.30049441 0.460332
 0.68552234 0.7786784  0.80323133 0.89906805]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [208]:
arr = np.arange(10)

import time
start = time.time()
np.add.reduce(arr)
end = time.time()
print(end - start)

start = time.time()
np.sum(arr)
end = time.time()
print(end - start)

8.893013000488281e-05
0.0002541542053222656


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [214]:
A = np.random.randint(0,10,10)
B = np.random.randint(0,10,10)
np.allclose(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [220]:
arr = np.random.randint(0,10,10)
arr.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [221]:
answer(44)

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [226]:
arr = np.random.random(10)
print(arr)
ind = arr.argmax()
arr[ind]=0

[0.7202911  0.93600038 0.29113451 0.24675225 0.92453987 0.49770904
 0.06553464 0.63617846 0.10139891 0.18888146]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [228]:
answer(46)

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [232]:
answer(47)

# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [239]:
print(np.iinfo(np.int8).min)
print(np.iinfo(np.int8).max)
print(np.iinfo(np.int32).min)
print(np.iinfo(np.int32).max)
print(np.iinfo(np.int64).min)
print(np.iinfo(np.int64).max)

print(np.finfo(np.float32).min)
print(np.finfo(np.float32).max)
print(np.finfo(np.float64).min)
print(np.finfo(np.float64).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [242]:
np.set_printoptions(threshold=float("inf"))
print(np.zeros((10,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [247]:
value = np.random.uniform(0,10)
arr = np.arange(10)
arr[(np.abs(arr-value)).argmin()]

5

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [250]:
np.zeros(1, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])

<ipython-input-250-692d8052c593>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np.zeros(1, [ ('position', [ ('x', float, 1),


array([((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [253]:
answer(52)

Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [256]:
(np.random.rand(10)*100).astype(np.float32).view(np.int32)

array([1115609136, 1108546022, 1102719373, 1115806626, 1118019139,
       1116712347, 1099707028, 1111238145, 1075763210, 1107583652],
      dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [257]:
answer(54)

from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [260]:
np.ndenumerate

numpy.ndenumerate

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [261]:
answer(56)

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [266]:
x=9
y=10
p = 2
Z = np.zeros((x,y))
print(Z)
np.put(Z, np.random.choice(range(x*y), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [270]:
X = np.random.rand(5, 10)
print(X)

X = X - X.mean(axis=1, keepdims=True)
print(X)

[[0.98630536 0.06191296 0.78488818 0.29558904 0.37328353 0.89380386
  0.24322633 0.35637474 0.30375907 0.97340397]
 [0.67447528 0.20895855 0.59302942 0.99126168 0.45592124 0.95985434
  0.11198816 0.91870543 0.11451364 0.61806859]
 [0.35009576 0.11502091 0.77060955 0.03005877 0.30703836 0.67034826
  0.39084284 0.91903408 0.29187792 0.03442934]
 [0.26219754 0.46724269 0.35427486 0.68391381 0.12273397 0.78280503
  0.55206798 0.9878197  0.67961627 0.6017294 ]
 [0.10840338 0.46833451 0.96062375 0.31577002 0.37651939 0.04847157
  0.13419884 0.72555866 0.20361166 0.90529817]]
[[ 0.45905065 -0.46534174  0.25763348 -0.23166566 -0.15397117  0.36654915
  -0.28402838 -0.17087996 -0.22349563  0.44614926]
 [ 0.10979765 -0.35571908  0.02835179  0.42658405 -0.10875639  0.39517671
  -0.45268947  0.3540278  -0.45016399  0.05339096]
 [-0.03783982 -0.27291467  0.38267397 -0.35787681 -0.08089722  0.28241268
   0.00290726  0.5310985  -0.09605766 -0.35350623]
 [-0.28724259 -0.08219744 -0.19516527  0.13447369

#### 59. How to sort an array by the nth column? (★★☆)

In [276]:
n = 2
arr[arr[:,n].argsort()]

array([[4, 1, 4],
       [0, 7, 7],
       [4, 3, 8]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [279]:
(~arr.any(axis=0)).any()

False

#### 61. Find the nearest value from a given value in an array (★★☆)

In [286]:
value = np.random.uniform(0,10)
arr = np.random.uniform(0,1, 10)
arr[(np.abs(arr-value)).argmin()]


0.9850094766457478

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [288]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [299]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

arr = NamedArray(np.arange(10), "range_10")
print (arr.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [304]:
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)
print(I)
np.add.at(Z, I, 1)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 6 6 8 8 0 8 0 7 8 5 1 1 9 1 9 6 7 5 0]
[5. 4. 1. 1. 1. 3. 4. 3. 5. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [311]:
X = np.arange(10).astype(int)
I = np.ones(10).astype(int)
F = np.bincount(I,X)
print(F)

[ 0. 45.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [313]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [316]:
A = np.random.randint(0,10,(3,4,3,4))
print(A)
A.sum(axis=(-2,-1))

[[[[7 7 0 7]
   [8 2 6 0]
   [7 1 8 2]]

  [[4 4 3 7]
   [4 8 4 0]
   [3 4 9 5]]

  [[0 8 8 0]
   [4 9 6 6]
   [6 2 9 2]]

  [[5 8 6 7]
   [0 5 9 9]
   [8 5 8 2]]]


 [[[0 9 7 1]
   [2 4 8 3]
   [7 1 4 6]]

  [[7 4 4 1]
   [1 7 7 5]
   [0 2 2 8]]

  [[4 6 0 8]
   [9 2 1 7]
   [7 8 7 8]]

  [[4 3 2 5]
   [0 9 6 3]
   [2 5 6 1]]]


 [[[5 7 7 9]
   [5 0 2 9]
   [0 8 7 0]]

  [[6 6 8 0]
   [9 9 2 1]
   [3 1 1 5]]

  [[2 0 1 1]
   [6 3 6 8]
   [2 4 1 6]]

  [[2 5 3 1]
   [1 0 2 8]
   [1 3 8 0]]]]


array([[55, 55, 60, 72],
       [52, 48, 67, 46],
       [59, 51, 40, 34]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [318]:
import pandas as pd
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
print(pd.Series(D).groupby(S).mean())

0    0.651732
1    0.386369
2    0.445364
3    0.497154
4    0.466586
5    0.526740
6    0.520790
7    0.567701
8    0.581399
9    0.398594
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [321]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.2074288 , 1.88377832, 0.75507451, 0.80828138, 0.99975678])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [326]:
arr = np.array([1,2,3,4,5])
arr_2 = np.zeros(len(arr) + ((len(arr)-1)*3))
print(arr_2)
arr_2[::4] = arr
print(arr_2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [335]:
A = np.ones((5,5,3))
B = np.arange(25).reshape(5,5)
print(A * B[:,:,None])

[[[ 0.  0.  0.]
  [ 1.  1.  1.]
  [ 2.  2.  2.]
  [ 3.  3.  3.]
  [ 4.  4.  4.]]

 [[ 5.  5.  5.]
  [ 6.  6.  6.]
  [ 7.  7.  7.]
  [ 8.  8.  8.]
  [ 9.  9.  9.]]

 [[10. 10. 10.]
  [11. 11. 11.]
  [12. 12. 12.]
  [13. 13. 13.]
  [14. 14. 14.]]

 [[15. 15. 15.]
  [16. 16. 16.]
  [17. 17. 17.]
  [18. 18. 18.]
  [19. 19. 19.]]

 [[20. 20. 20.]
  [21. 21. 21.]
  [22. 22. 22.]
  [23. 23. 23.]
  [24. 24. 24.]]]


#### 72. How to swap two rows of an array? (★★★)

In [340]:
A = np.arange(25).reshape(5,5)
print(A)
first = A[[1,0]]
second = A[[0,1]] 
A[[0,1]] = first
A[[1,0]] = second
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [342]:
answer(73)

# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [344]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [345]:
answer(75)

# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

# Author: Jeff Luo (@Jeff1999)
# make sure your NumPy >= 1.20.0

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [349]:
answer(76)

# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

# Author: Jeff Luo (@Jeff1999)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [347]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.40150931,  0.5399058 , -0.35475997,  0.43128051,  0.15516877,
        0.69688766, -0.35861084, -0.45780681, -0.21853787, -0.1714437 ,
       -0.07962454,  0.93373448, -0.12450892,  0.61842472,  0.42201302,
       -0.25675373, -0.17166689, -0.16920498,  0.10214196,  0.63202297,
        0.19348252,  0.54532941, -0.21375947,  0.99090804, -0.12465376,
        0.03208301, -0.06182609,  0.57454229,  0.70572507, -0.64116186,
        0.41815245, -0.77321635,  0.38286942, -0.58833858, -0.57543644,
       -0.61470827,  0.99106382, -0.48061569,  0.7122135 ,  0.23198406,
       -0.450341  ,  0.8604068 , -0.98438401,  0.06084082,  0.97728753,
        0.95620078, -0.27618254,  0.96761803,  0.17157372, -0.62441603,
        0.65966194,  0.93618548, -0.22609222,  0.33630422, -0.54353336,
       -0.57513028,  0.85913425, -0.06480915,  0.08822827, -0.70500347,
        0.08013373,  0.89631536, -0.82480318,  0.21682405, -0.67044132,
        0.92209256,  0.67979282, -0.35499017, -0.24389327,  0.73

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [353]:
P0 = np.random.uniform(1,10,(10,2))
P1 = np.random.uniform(1,10,(10,2))
p  = np.random.uniform(1,10,( 1,2))
P0

array([[2.73287679, 1.96490569],
       [6.24386287, 5.34502181],
       [1.09305727, 5.18794858],
       [5.54026673, 3.90242692],
       [5.7190791 , 6.82660549],
       [9.85505336, 6.59350528],
       [7.27266855, 8.65065016],
       [7.37286548, 8.55148112],
       [7.61047666, 7.24199913],
       [5.19610215, 6.2255969 ]])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [351]:
answer(79)

# Author: Italmassov Kuanysh

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [354]:
answer(80)

# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [361]:
arr = np.arange(1, 15)
print(np.lib.stride_tricks.sliding_window_view(arr, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [371]:
arr = np.random.uniform(0,10,(5,5))
np.linalg.matrix_rank(arr)

5

#### 83. How to find the most frequent value in an array?

In [378]:
arr = np.random.randint(0,10,10)
np.bincount(arr).argmax()

6

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [382]:
arr = np.random.randint(0,10,(10,10))
np.lib.stride_tricks.sliding_window_view(arr, window_shape=(3, 3))

array([[[[8, 3, 0],
         [0, 8, 7],
         [2, 3, 5]],

        [[3, 0, 7],
         [8, 7, 1],
         [3, 5, 7]],

        [[0, 7, 3],
         [7, 1, 6],
         [5, 7, 6]],

        [[7, 3, 8],
         [1, 6, 8],
         [7, 6, 9]],

        [[3, 8, 2],
         [6, 8, 1],
         [6, 9, 3]],

        [[8, 2, 2],
         [8, 1, 8],
         [9, 3, 9]],

        [[2, 2, 7],
         [1, 8, 7],
         [3, 9, 1]],

        [[2, 7, 0],
         [8, 7, 8],
         [9, 1, 8]]],


       [[[0, 8, 7],
         [2, 3, 5],
         [2, 5, 0]],

        [[8, 7, 1],
         [3, 5, 7],
         [5, 0, 0]],

        [[7, 1, 6],
         [5, 7, 6],
         [0, 0, 0]],

        [[1, 6, 8],
         [7, 6, 9],
         [0, 0, 6]],

        [[6, 8, 1],
         [6, 9, 3],
         [0, 6, 4]],

        [[8, 1, 8],
         [9, 3, 9],
         [6, 4, 1]],

        [[1, 8, 7],
         [3, 9, 1],
         [4, 1, 2]],

        [[8, 7, 8],
         [9, 1, 8],
         [1, 2, 0]]],


    

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [383]:
answer(85)

# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [400]:
arr = np.ones((16, 16))*2
print(np.lib.stride_tricks.sliding_window_view(arr, window_shape=(4, 4))[::4, ::4].sum(axis=(-2, -1)))

[[32. 32. 32. 32.]
 [32. 32. 32. 32.]
 [32. 32. 32. 32.]
 [32. 32. 32. 32.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [395]:
answer(88)

# Author: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)


#### 89. How to get the n largest values of an array (★★★)

In [394]:
arr = np.random.randint(0,100,10)
print(arr)
n = 3
print(np.sort(arr)[-n:])

[36 68 96  1 73 45 74 71  0 45]
[73 74 96]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [406]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [403]:
answer(91)

Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [410]:
arr = np.random.rand(int(10000))
%timeit np.power(arr,3)
%timeit arr*arr*arr
%timeit arr**3

297 µs ± 22.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
12.5 µs ± 1.04 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
292 µs ± 6.38 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [427]:
answer(93)

# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [426]:
answer(94)

# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [425]:
answer(95)

# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [424]:
arr = np.random.randint(0,2,(10,2))
np.unique(arr, axis=0)

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [417]:
A = np.random.uniform(0,10,10)
B = np.random.uniform(0,10,10)

np.einsum('i->', A)
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B) 

array([[33.44013757, 43.63726066, 50.45788677, 44.62920478, 24.52101839,
        51.24777573, 48.91286615, 13.67079312, 44.23903936, 29.70109806],
       [17.94892524, 23.42221014, 27.08316722, 23.95463411, 13.16160632,
        27.50713849, 26.25388057,  7.33777016, 23.74521363, 15.94200345],
       [33.47088656, 43.67738614, 50.50428398, 44.67024237, 24.54356604,
        51.29489926, 48.95784267, 13.68336373, 44.27971819, 29.72840891],
       [32.33186613, 42.19103665, 48.7856139 , 43.1501058 , 23.70834397,
        49.54932439, 47.29179827, 13.21771634, 42.77287123, 28.71674569],
       [ 3.36513396,  4.3912866 ,  5.07765699,  4.4911075 ,  2.46758888,
         5.15714477,  4.92217912,  1.37571355,  4.45184454,  2.9888685 ],
       [47.77118031, 62.33836338, 72.08202425, 63.75541321, 35.02970011,
        73.21042654, 69.87487248, 19.52952262, 63.19803924, 42.42974503],
       [34.97231675, 45.63665741, 52.76979484, 46.67405098, 25.64453631,
        53.59587537, 51.15398358, 14.29716927

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [413]:
answer(98)

# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [412]:
answer(99)

# Author: Evgeni Burovski

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [411]:
answer(100)

# Author: Jessica B. Hamrick

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)
